### ISSUE TITLE
Type Error When Running Example

### ISSUE THREAD

**Issue by Mikesev** [flennerhag/mlens#33] opened 2017-07-11 19:55 UTC
Hi,

I'm trying to run the Getting Started example and am hitting the following error, code and trace below:

Code:

`import numpy as np
from pandas import DataFrame
from mlens.metrics import make_scorer
from sklearn.metrics import f1_score
from sklearn.datasets import load_iris

seed = 2017
np.random.seed(seed)

f1 = make_scorer(f1_score, average='micro', greater_is_better=True)

data = load_iris()
idx = np.random.permutation(150)
X = data.data[idx]
y = data.target[idx]

from mlens.ensemble import SuperLearner
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# --- Build ---

# Passing a scorer will create cv scores during fitting
ensemble = SuperLearner(scorer=f1, random_state=seed)

# Build the first layer
ensemble.add([RandomForestClassifier(random_state=seed), SVC()])

# Attach the final meta estimator
ensemble.add_meta(LogisticRegression())

# --- Use ---

# Fit ensemble
ensemble.fit(X[:75], y[:75])

# Predict
preds = ensemble.predict(X[75:])
`

Error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-0acd47b3d82b> in <module>()
     18 
     19 # Fit ensemble
---> 20 ensemble.fit(X[:75], y[:75])
     21 
     22 # Predict

C:\Anaconda2\lib\site-packages\mlens\ensemble\base.pyc in fit(self, X, y)
    714             X, y = X[idx], y[idx]
    715 
--> 716         self.scores_ = self.layers.fit(X, y)
    717 
    718         return self

C:\Anaconda2\lib\site-packages\mlens\ensemble\base.pyc in fit(self, X, y, return_preds, **process_kwargs)
    232         # Fit ensemble
    233         try:
--> 234             processor.process()
    235 
    236             if self.verbose:

C:\Anaconda2\lib\site-packages\mlens\parallel\manager.pyc in process(self)
    216 
    217             for n, lyr in enumerate(self.layers.layers.values()):
--> 218                 self._partial_process(n, lyr, parallel)
    219 
    220         self.__fitted__ = 1

C:\Anaconda2\lib\site-packages\mlens\parallel\manager.pyc in _partial_process(self, n, lyr, parallel)
    306             kwargs['P'] = self.job.P[n + 1]
    307 
--> 308         f(**kwargs)
    309 
    310 

C:\Anaconda2\lib\site-packages\mlens\parallel\estimation.pyc in fit(self, X, y, P, dir, parallel)
    198         # Load instances from cache and store as layer attributes
    199         # Typically, as layer.estimators_, layer.preprocessing_
--> 200         self._assemble(dir)
    201 
    202         if self.verbose:

C:\Anaconda2\lib\site-packages\mlens\parallel\estimation.pyc in _assemble(self, dir)
     93 
     94         if self.scorer is not None and self.layer.cls is not 'full':
---> 95             self.layer.scores_ = self._build_scores(s)
     96 
     97     def _build_scores(self, s):

C:\Anaconda2\lib\site-packages\mlens\parallel\estimation.pyc in _build_scores(self, s)
    126         # Aggregate to get cross-validated mean scores
    127         for k, v in scores.items():
--> 128             scores[k] = (np.mean(v), np.std(v))
    129 
    130         return scores

C:\Anaconda2\lib\site-packages\numpy\core\fromnumeric.pyc in mean(a, axis, dtype, out, keepdims)
   2940 
   2941     return _methods._mean(a, axis=axis, dtype=dtype,
-> 2942                             out=out, **kwargs)
   2943 
   2944 

C:\Anaconda2\lib\site-packages\numpy\core\_methods.pyc in _mean(a, axis, dtype, out, keepdims)
     63         dtype = mu.dtype('f8')
     64 
---> 65     ret = umr_sum(arr, axis, dtype, out, keepdims)
     66     if isinstance(ret, mu.ndarray):
     67         ret = um.true_divide(

TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

**Comment by flennerhag** [comment] 2017-07-12 08:46
Oops, the *getting started* docs was not up to date! The scorer should be a simple function, like 

```
def scorer(y_true, y_pred):
    # do some arthimetic
    return scalar
```

So if you define the scorer (``f1``) as

```
def f1(y_true, y_pred):
    return f1_score(y_true, y_pred, average='micro')
```

You should be fine (works on my machine). I'll update the documentation when I get a chance! 
Let me know if it works and I'll close the issue.

**Comment by Mikesev** [comment] 2017-07-12 10:22
Thanks for the quick response! Maybe I'm missing a crucial point but this throws up an attribute error, just including the key lines:

`
def f1(y_true, y_pred):
    return f1_score(y_true, y_pred, average='micro')

ensemble = SuperLearner(scorer=f1, random_state=seed)
...
ensemble.fit(X[:75], y[:75])
`

Process PoolWorker-6:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Anaconda2\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda2\lib\multiprocessing\pool.py", line 102, in worker
    task = get()
  File "C:\Anaconda2\lib\site-packages\mlens\externals\joblib\pool.py", line 362, in get
    return recv()
AttributeError: 'module' object has no attribute 'f1'

**Comment by flennerhag** [comment] 2017-07-12 12:09
Hm that makes no sense... 

The following works fine for me: 

```
import numpy as np
from pandas import DataFrame
from sklearn.metrics import f1_score
from sklearn.datasets import load_iris
from mlens.ensemble import SuperLearner
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

seed = 2017
np.random.seed(seed)

def f1(y, p): return f1_score(y, p, average='micro')

data = load_iris()
idx = np.random.permutation(150)
X = data.data[idx]
y = data.target[idx]

ensemble = SuperLearner(scorer=f1, random_state=seed)
ensemble.add([RandomForestClassifier(random_state=seed), SVC()])
ensemble.add_meta(LogisticRegression())
ensemble.fit(X[:75], y[:75])
```

Using a scoring function is unit-tested on Mac, Linux and Windows (in Python 3), so if you still have an issue the problem is more fundamental. If the above code doesn't work for you, could you send over a minimum code example that throws error? 

It looks like you are running on Windows, which Python version are you using?

**Comment by Mikesev** [comment] 2017-07-12 14:47
You're correct, I'm on Windows and the above output was from Python 2.7. I just installed Python 3.6 and reran the script, it's giving out a very similar error:

Process SpawnPoolWorker-9:
Traceback (most recent call last):
  File "C:\Anaconda2\envs\py36\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Anaconda2\envs\py36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda2\envs\py36\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Anaconda2\envs\py36\lib\site-packages\mlens\externals\joblib\pool.py", line 362, in get
    return recv()
  File "C:\Anaconda2\envs\py36\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'f1_scorer' on <module '__main__' (built-in)>

**Comment by Mikesev** [comment] 2017-07-12 15:11
You're correct, I'm on Windows and the above output was from Python 2.7. I just installed Python 3.6 and reran the script, it's giving out a very similar error:

Process SpawnPoolWorker-9:
Traceback (most recent call last):
File "C:\Anaconda2\envs\py36\lib\multiprocessing\process.py", line 249, in _bootstrap
self.run()
File "C:\Anaconda2\envs\py36\lib\multiprocessing\process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "C:\Anaconda2\envs\py36\lib\multiprocessing\pool.py", line 108, in worker
task = get()
File "C:\Anaconda2\envs\py36\lib\site-packages\mlens\externals\joblib\pool.py", line 362, in get
return recv()
File "C:\Anaconda2\envs\py36\lib\multiprocessing\connection.py", line 251, in recv
return _ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'f1' on <module 'main' (built-in)>

Narrowing this down, setting n_jobs =1 does not throw the error! So this seems to be a problem with the multi threading, see notebook for details. Looks like this might be relevant: https://stackoverflow.com/questions/41385708/multiprocessing-example-giving-attributeerror

I'll try and dig further and see if I can engineer a fix.

[Untitled2.zip](https://github.com/flennerhag/mlens/files/1142451/Untitled2.zip)

**Comment by flennerhag** [comment] 2017-07-12 15:38
@Mikesev thanks for debugging! I'm not getting this error on OSX, so I suspect this is Windows specific. Could I ask you to try two things? 

1. set ``backend='threading'`` in the ensemble. When ``n_jobs!=1`` with multiprocessing, the parent process is copied to sub-processes. By using threading instead, all computations are  handled by the parent process so the scoring function should be accessible.

2. If this doesn't work, could you try installing the developer version (to be version 0.1.4), there are some bug-fixes there that would be good to rule out? To do this, run:

```
git clone https://flennerhag/mlens.git; cd mlens;
python install setup.py
```

Thanks!

**Comment by Mikesev** [comment] 2017-07-12 15:44
No worries! Yep, I will do so.

It definitely seems to be related to the Pool issue that's raised on the SO post and elaborated on here: https://bugs.python.org/issue25053. 

I just imported the f1 function from a separate file and it worked straight away with n_jobs = -1.

**Comment by Mikesev** [comment] 2017-07-12 15:49
1. set `backend='threading'` in the ensemble

This works!

**Comment by flennerhag** [comment] 2017-07-12 16:42
Great! Threading will be default from 0.1.4 so I will close this issue. Thanks for the debugging : )

**Closed by flennerhag** 2017-07-12 16:42 UTC
